# Generated by Django 3.0.4 on 2020-03-24 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tutorals',
            new_name='Tutorials',
        ),
    ]
